"""add expense notes

Revision ID: 006
Revises: 005
Create Date: 2026-03-26 22:40:32.128825

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "006"
down_revision: str | None = "005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense_notes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("expense_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("expense_notes_author_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
            name=op.f("expense_notes_expense_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("expense_notes_pkey")),
    )
    op.create_index(
        op.f("ix_expense_notes_author_id"), "expense_notes", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_expense_notes_expense_id"), "expense_notes", ["expense_id"], unique=False
    )
    op.create_index(
        op.f("ix_expense_notes_expense_id_created_at"),
        "expense_notes",
        ["expense_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expense_notes_expense_id_created_at"), table_name="expense_notes")
    op.drop_index(op.f("ix_expense_notes_expense_id"), table_name="expense_notes")
    op.drop_index(op.f("ix_expense_notes_author_id"), table_name="expense_notes")
    op.drop_table("expense_notes")
    # ### end Alembic commands ###
