"""add_groups_and_memberships

Revision ID: 6851f09a03b6
Revises: 001
Create Date: 2026-03-16 22:13:07.568934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6851f09a03b6'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('default_currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('default_split_type', sa.Enum('EVEN', name='splittype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('singleton_guard', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('tracking_threshold', sa.Integer(), nullable=False, server_default=sa.text('30')),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('singleton_guard', name='uq_groups_singleton_guard')
    )
    op.create_table('group_memberships',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='memberrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_memberships')
    op.drop_table('groups')
    # ### end Alembic commands ###
