"""add_missing_group_fields

Revision ID: e46e0337f54d
Revises: 6851f09a03b6
Create Date: 2026-03-17 00:18:12.072638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46e0337f54d'
down_revision: Union[str, None] = '6851f09a03b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('tracking_threshold', sa.Integer(), nullable=False))
    op.add_column('groups', sa.Column('singleton_guard', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'groups', ['singleton_guard'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_column('groups', 'singleton_guard')
    op.drop_column('groups', 'tracking_threshold')
    # ### end Alembic commands ###
